<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>78a6cfcc-2fcb-435a-93d3-5b976c7dc0c4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Ridder.Aspire.Hosting.Dokploy/Ridder.Aspire.Hosting.Dokploy.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
