<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>1dc1ea36-207d-4708-ba4b-f3ae6bf4d9f1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../SimpleWebApp.ApiService/SimpleWebApp.ApiService.csproj" />
    <ProjectReference Include="../../../src/Ridder.Hosting.Dokploy/Ridder.Hosting.Dokploy.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
